/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import entidade.Fornecedor;
import entidade.FornecedorDao;
import estoque.MovimentacaoEstoque;
import estoque.MovimentacaoEstoqueDao;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import produto.ProdutoAcabado;
import produto.ProdutoCongelado;
import produto.ProdutoCongeladoDao;

/**
 *
 * @author LUKAS
 */
public class Estoque extends javax.swing.JFrame {

    MovimentacaoEstoque movimentacaoEstoque = new MovimentacaoEstoque();
    MovimentacaoEstoqueDao movimentacaoEstoqueDao = new MovimentacaoEstoqueDao();
    ProdutoCongeladoDao congeladoDao = new ProdutoCongeladoDao();
    ProdutoCongelado produtoCongelado = new ProdutoCongelado();
    ProdutoAcabado produtoAcabado = new ProdutoAcabado();
    Fornecedor fornecedor = new Fornecedor();
    FornecedorDao fornecedorDao = new FornecedorDao();
    LocalDate data = LocalDate.now();
    DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    /**
     * Creates new form TransferenciaEstoque
     */
    public Estoque() {
        initComponents();
        jbExcluir.setEnabled(false);
        jbSalvar.setEnabled(false);
        txtData.setEditable(false);
        txtNomeFornecedor.setEditable(false);
        txtNomeProdutoCongelado.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbTransferencia = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbBuscar = new javax.swing.JButton();
        jbIncluir = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jlID2 = new javax.swing.JLabel();
        txtNomeProdutoCongelado = new javax.swing.JTextField();
        jlProduto1 = new javax.swing.JLabel();
        txtIdProdutoCongelado = new javax.swing.JTextField();
        jlQuantidade1 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jlID3 = new javax.swing.JLabel();
        txtNomeFornecedor = new javax.swing.JTextField();
        jlProduto2 = new javax.swing.JLabel();
        txtIdFornecedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtData = new javax.swing.JTextField();
        jlID1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtOperacaoNome = new javax.swing.JTextField();
        jlID = new javax.swing.JLabel();
        jlID4 = new javax.swing.JLabel();
        txtOperacao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ESTOQUE - Congelado");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("VOLTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbTransferencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbTransferencia.setText("TRANSFERÊNCIA");
        jbTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTransferenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                .addComponent(jbTransferencia)
                .addGap(65, 65, 65)
                .addComponent(jButton1)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jbTransferencia))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 800));

        jbBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbIncluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbIncluir.setText("Incluir");
        jbIncluir.setNextFocusableComponent(txtOperacao);
        jbIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIncluirActionPerformed(evt);
            }
        });

        jbSalvar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbBuscar)
                    .addComponent(jbIncluir)
                    .addComponent(jbSalvar)
                    .addComponent(jbExcluir)
                    .addComponent(btnLimpar))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jbBuscar)
                .addGap(50, 50, 50)
                .addComponent(jbIncluir)
                .addGap(50, 50, 50)
                .addComponent(jbSalvar)
                .addGap(50, 50, 50)
                .addComponent(jbExcluir)
                .addGap(50, 50, 50)
                .addComponent(btnLimpar)
                .addContainerGap(341, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(945, 800));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlID2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlID2.setText("ID");

        txtNomeProdutoCongelado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNomeProdutoCongelado.setFocusable(false);

        jlProduto1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlProduto1.setText("Produto");

        txtIdProdutoCongelado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIdProdutoCongelado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdProdutoCongeladoFocusLost(evt);
            }
        });
        txtIdProdutoCongelado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdProdutoCongeladoKeyPressed(evt);
            }
        });

        jlQuantidade1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlQuantidade1.setText("Quantidade");

        txtQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtQuantidade.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jlID3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlID3.setText("ID");

        txtNomeFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNomeFornecedor.setFocusable(false);

        jlProduto2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlProduto2.setText("Fornecedor");

        txtIdFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIdFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFornecedorFocusLost(evt);
            }
        });
        txtIdFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdFornecedorKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("KG");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlID3)
                            .addComponent(txtIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlProduto2)
                            .addComponent(txtNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlID2)
                            .addComponent(txtIdProdutoCongelado, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlProduto1)
                            .addComponent(txtNomeProdutoCongelado, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jlQuantidade1))
                .addGap(47, 47, 47))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlProduto2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlID3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlProduto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeProdutoCongelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlID2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdProdutoCongelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jlQuantidade1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(97, 97, 97))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtData.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlID1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlID1.setText("Data");

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtOperacaoNome.setEditable(false);
        txtOperacaoNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtOperacaoNome.setFocusable(false);

        jlID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlID.setText("ID");

        jlID4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlID4.setText("Operação");

        txtOperacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtOperacao.setNextFocusableComponent(txtIdFornecedor);
        txtOperacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOperacaoFocusLost(evt);
            }
        });
        txtOperacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOperacaoKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setText("(1 - Entrada / 2 - Saída)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlID)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jlID4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOperacaoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(164, 164, 164)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlID1)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jlID)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jlID1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlID4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOperacaoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Principal principal = new Principal();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIncluirActionPerformed
        boolean status = movimentacaoEstoqueDao.conectar();

        if (status == true) {
            txtId.setText(Integer.toString(movimentacaoEstoqueDao.ProximoId() + 1));
            txtId.setEditable(false);
            txtOperacaoNome.setText("");
            txtOperacao.setText("");
            String strData = data.format(fmt);
            txtData.setText(strData);
            txtIdFornecedor.setText("");
            txtNomeFornecedor.setText("");
            txtIdProdutoCongelado.setText("");
            txtNomeProdutoCongelado.setText("");
            txtQuantidade.setText("");
            jbSalvar.setEnabled(true);
            jbIncluir.nextFocus();
            movimentacaoEstoqueDao.desconectar();
            return;
        }

    }//GEN-LAST:event_jbIncluirActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        int id = 0;
        int operacao = 0;
        String strData = "";
        LocalDate data = this.data;
        int idFornecedor = 0;
        String nomeFornecedor = "";
        int idProduto = 0;
        String nomeProduto = "";
        double quantidade = 0.0;
        String operacaoNome = "";
        boolean status = movimentacaoEstoqueDao.conectar();
        int resposta;
        java.sql.Date sqlDate = null;

        try {
            id = Integer.parseInt(txtId.getText());
            operacao = Integer.parseInt(txtOperacao.getText());
            strData = txtData.getText();
            data = LocalDate.parse(strData, fmt);
            idFornecedor = Integer.parseInt(txtIdFornecedor.getText());
            nomeFornecedor = txtNomeFornecedor.getText();
            idProduto = Integer.parseInt(txtIdProdutoCongelado.getText());
            nomeProduto = txtNomeProdutoCongelado.getText();
            quantidade = Double.parseDouble(txtQuantidade.getText());
            operacaoNome = txtOperacaoNome.getText();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Preencha os campos corretamente!");
            return;
        }

        if (!nomeFornecedor.equals("") && !nomeProduto.equals("")) {
            if (operacao == 1) {
                if (status == false) {
                    JOptionPane.showMessageDialog(null, "Erro de conexão");
                } else {

                    SimpleDateFormat conversor = new SimpleDateFormat("dd/MM/yyyy");
                    try {
                        Date dataConvertida = conversor.parse(strData);
                        sqlDate = new java.sql.Date(dataConvertida.getTime());
                    } catch (ParseException e) {
                        System.out.println("Erro na conversão da data");
                    }
                    Fornecedor fornecedor = new Fornecedor();
                    fornecedor.setId(idFornecedor);
                    ProdutoCongelado congelado = new ProdutoCongelado();
                    congelado.setId(idProduto);
                    MovimentacaoEstoque estoque = new MovimentacaoEstoque(id, quantidade, operacao, operacaoNome, fornecedor, congelado, sqlDate);
                    resposta = movimentacaoEstoqueDao.salvarCongelado(estoque);

                    if (resposta == 1) {
                        JOptionPane.showMessageDialog(rootPane, "Entrada realizada com sucesso!");
                    } else if (resposta == 1062) {
                        JOptionPane.showMessageDialog(null, "Dados já cadastrado");
                    }
                    jbSalvar.setEnabled(false);
                    movimentacaoEstoqueDao.desconectar();
                }

            } else if (operacao == 2) {
                if (status == false) {
                    JOptionPane.showMessageDialog(null, "Erro de conexão");
                } else {

                    SimpleDateFormat conversor = new SimpleDateFormat("dd/MM/yyyy");
                    try {
                        Date dataConvertida = conversor.parse(strData);
                        sqlDate = new java.sql.Date(dataConvertida.getTime());
                    } catch (ParseException e) {
                        System.out.println("Erro na conversão da data");
                    }
                    Fornecedor fornecedor = new Fornecedor();
                    fornecedor.setId(idFornecedor);
                    ProdutoCongelado congelado = new ProdutoCongelado();
                    congelado.setId(idProduto);
                    MovimentacaoEstoque estoque = new MovimentacaoEstoque(id, quantidade, operacao, operacaoNome, fornecedor, congelado, sqlDate);
                    resposta = movimentacaoEstoqueDao.salvarCongelado(estoque);

                    if (resposta == 1) {
                        JOptionPane.showMessageDialog(rootPane, "Saída realizada com sucesso!");
                    } else if (resposta == 1062) {
                        JOptionPane.showMessageDialog(null, "Dados já cadastrado");
                    }
                    jbSalvar.setEnabled(false);
                    movimentacaoEstoqueDao.desconectar();
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Preencha os campos corretamente");
                return;
            }
            limparTela();
            txtId.setEditable(true);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void txtIdProdutoCongeladoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdProdutoCongeladoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int idProdutoCongelado = 0;
            boolean status = congeladoDao.conectar();
            try {
                idProdutoCongelado = Integer.parseInt(txtIdProdutoCongelado.getText());
            } catch (NumberFormatException e) {
            }
            if (idProdutoCongelado == 0) {
                return;
            }
            if (status == true) {
                ProdutoCongelado congelado = new ProdutoCongelado();
                congelado = congeladoDao.consultar(idProdutoCongelado);

                txtNomeProdutoCongelado.setText(congelado.getNome());
                movimentacaoEstoqueDao.desconectar();
            }
        }
    }//GEN-LAST:event_txtIdProdutoCongeladoKeyPressed

    private void txtIdProdutoCongeladoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdProdutoCongeladoFocusLost
        int idProdutoCongelado = 0;
        boolean status = congeladoDao.conectar();
        try {
            idProdutoCongelado = Integer.parseInt(txtIdProdutoCongelado.getText());
        } catch (NumberFormatException e) {
            return;
        }
        if (idProdutoCongelado == 0) {
            return;
        }
        if (status == true) {
            ProdutoCongelado congelado = new ProdutoCongelado();
            congelado = congeladoDao.consultar(idProdutoCongelado);

            txtNomeProdutoCongelado.setText(congelado.getNome());
            movimentacaoEstoqueDao.desconectar();
        }
    }//GEN-LAST:event_txtIdProdutoCongeladoFocusLost

    private void txtIdFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFornecedorFocusLost
        int id = 0;
        boolean status = fornecedorDao.conectar();
        try {
            id = Integer.parseInt(txtIdFornecedor.getText());
        } catch (NumberFormatException e) {

        }
        if (id == 0) {
            return;
        }
        if (status == true) {
            Fornecedor f = new Fornecedor();
            f = fornecedorDao.consultar(id);
            txtNomeFornecedor.setText(f.getNomeEmpresa());
            movimentacaoEstoqueDao.desconectar();
        }
    }//GEN-LAST:event_txtIdFornecedorFocusLost

    private void txtIdFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdFornecedorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int id = 0;
            boolean status = fornecedorDao.conectar();
            try {
                id = Integer.parseInt(txtIdFornecedor.getText());
            } catch (NumberFormatException e) {

            }
            if (id == 0) {
                return;
            }
            if (status == true) {
                Fornecedor f = new Fornecedor();
                f = fornecedorDao.consultar(id);
                txtNomeFornecedor.setText(f.getNomeEmpresa());
                movimentacaoEstoqueDao.desconectar();
            }
        }
    }//GEN-LAST:event_txtIdFornecedorKeyPressed

    private void txtOperacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOperacaoFocusLost
        int operacao = 0;
        String entrada = "Entrada";
        String saida = "Saída";

        try {
            operacao = Integer.parseInt(txtOperacao.getText());
        } catch (NumberFormatException e) {

        }
        if (operacao == 1) {
            txtOperacaoNome.setText(entrada);
        } else if (operacao == 2) {
            txtOperacaoNome.setText(saida);
        } else {
            txtOperacaoNome.setText("");
        }
    }//GEN-LAST:event_txtOperacaoFocusLost

    private void txtOperacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOperacaoKeyPressed
        int operacao = 0;
        String entrada = "Entrada";
        String saida = "Saída";
        try {
            operacao = Integer.parseInt(txtOperacao.getText());
        } catch (NumberFormatException e) {

        }

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (operacao == 1) {
                txtOperacaoNome.setText(entrada);
            } else if (operacao == 2) {
                txtOperacaoNome.setText(saida);
            } else {
                txtOperacaoNome.setText("");
            }
        }
    }//GEN-LAST:event_txtOperacaoKeyPressed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        int id = 0;
        boolean status = movimentacaoEstoqueDao.conectar();
        try {
            id = Integer.parseInt(txtId.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Formato Inválido!");
        }

        if (status == true) {
            MovimentacaoEstoque estoque = movimentacaoEstoqueDao.consultarCongelado(id);
            if (estoque == null) {
                JOptionPane.showMessageDialog(null, "Não foi encontrado uma movimentação com ID " + id + "");
            } else {
                txtOperacao.setText(Integer.toString(estoque.getOperacao()));
                txtOperacao.setEditable(false);
                txtOperacaoNome.setText(estoque.getOperacaoNome());
                txtOperacaoNome.setEditable(false);
                txtData.setText(this.reverterData(String.valueOf(estoque.getData())));
                txtData.setEditable(false);
                txtIdFornecedor.setText(Integer.toString(estoque.getFornecedor().getId()));
                txtIdFornecedor.setEditable(false);
                txtNomeFornecedor.setText(estoque.getFornecedor().getNomeEmpresa());
                txtNomeFornecedor.setEditable(false);
                txtIdProdutoCongelado.setText(Integer.toString(estoque.getProdutoCongelado().getId()));
                txtIdProdutoCongelado.setEditable(false);
                txtNomeProdutoCongelado.setText(estoque.getProdutoCongelado().getNome());
                txtNomeProdutoCongelado.setEditable(false);
                txtQuantidade.setText(Double.toString(estoque.getQuantidade()));
                txtQuantidade.setEditable(false);
                jbExcluir.setEnabled(true);
                return;
            }
            movimentacaoEstoqueDao.desconectar();
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        Object[] options = {"OK", "CANCELAR"};
        int id = 0;
        boolean status = movimentacaoEstoqueDao.conectar();
        try {
            id = Integer.parseInt(txtId.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Formato Inválido");
        }
        if (status == false) {
            JOptionPane.showMessageDialog(null, "Erro de conexão");
        } else {
            MovimentacaoEstoque movimentacaoEstoque = movimentacaoEstoqueDao.consultarCongelado(id);
            if (movimentacaoEstoque == null) {
                JOptionPane.showMessageDialog(rootPane, "Movimentação com ID: " + id + " não encontrado");
            } else {
                int confirmação = JOptionPane.showOptionDialog(null, "Deseja excluir a Movimentação: \nID:" + movimentacaoEstoque.getId() + "\nNome do Produto: " + movimentacaoEstoque.getProdutoCongelado().getNome() + "\nOperação: " + movimentacaoEstoque.getOperacaoNome() + "\nQuantidade: " + movimentacaoEstoque.getQuantidade(),
                        "Aviso", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
                if (confirmação == 0) {
                    status = movimentacaoEstoqueDao.excluir(id);
                    JOptionPane.showMessageDialog(rootPane, "Movimentação: " + id + "\nNome do Produto: " + movimentacaoEstoque.getProdutoCongelado().getNome() + "\nOperação: " + movimentacaoEstoque.getOperacaoNome() + "\nQuantidade: " + movimentacaoEstoque.getQuantidade()
                            + "\n\nRemovido com sucesso!");
                    limparTela();
                    movimentacaoEstoqueDao.desconectar();
                    return;
                } else if (confirmação == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Exclusão cancelada");
                    movimentacaoEstoqueDao.desconectar();
                    return;
                }
            }
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTransferenciaActionPerformed
        TransferenciaEstoque estoque = new TransferenciaEstoque();
        estoque.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbTransferenciaActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparTela();
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbIncluir;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbTransferencia;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlID1;
    private javax.swing.JLabel jlID2;
    private javax.swing.JLabel jlID3;
    private javax.swing.JLabel jlID4;
    private javax.swing.JLabel jlProduto1;
    private javax.swing.JLabel jlProduto2;
    private javax.swing.JLabel jlQuantidade1;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdFornecedor;
    private javax.swing.JTextField txtIdProdutoCongelado;
    private javax.swing.JTextField txtNomeFornecedor;
    private javax.swing.JTextField txtNomeProdutoCongelado;
    private javax.swing.JTextField txtOperacao;
    private javax.swing.JTextField txtOperacaoNome;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
     public String reverterData(String data) {
        String dia = data.substring(8);
        String mes = data.substring(5, 7);
        String ano = data.substring(0, 4);
        String sqlDate = dia + "/" + mes + "/" + ano;
        return sqlDate;
    }

    public void limparTela() {
        txtData.setText("");
        txtId.setText("");
        txtIdFornecedor.setText("");
        txtIdProdutoCongelado.setText("");
        txtNomeFornecedor.setText("");
        txtNomeProdutoCongelado.setText("");
        txtOperacao.setText("");
        txtOperacaoNome.setText("");
        txtQuantidade.setText("");
        jbBuscar.setEnabled(false);
        jbSalvar.setEnabled(false);
        txtId.requestFocus();
    }
}
