/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import entidade.Fornecedor;
import entidade.FornecedorDao;
import javax.swing.JOptionPane;

/**
 *
 * @author LUKAS
 */
public class telaFornecedor extends javax.swing.JFrame {

    public static RelatorioFornecedor relatorioFornecedor = new RelatorioFornecedor();
    FornecedorDao fornecedorDao = new FornecedorDao();
    Fornecedor fornecedor = new Fornecedor();

    /**
     * Creates new form Fornecedor
     */
    public telaFornecedor() {
        initComponents();
        jbExcluir.setEnabled(false);
        jbSalvar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbBuscar = new javax.swing.JButton();
        jbIncluir = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbRelatorio = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlID = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jlCNPJ = new javax.swing.JLabel();
        jlUF = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        jlTelefone = new javax.swing.JLabel();
        jlEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jlEmail1 = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtUF = new javax.swing.JTextField();
        jlUF1 = new javax.swing.JLabel();
        jlEmail2 = new javax.swing.JLabel();
        txtNumeroEndereco = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 100));

        jbVoltar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbVoltar.setText("VOLTAR");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("FORNECEDOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 588, Short.MAX_VALUE)
                .addComponent(jbVoltar)
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbVoltar)
                    .addComponent(jLabel1))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(150, 800));

        jbBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbIncluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbIncluir.setText("Incluir");
        jbIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIncluirActionPerformed(evt);
            }
        });

        jbSalvar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbRelatorio.setText("Relatório");
        jbRelatorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRelatorioActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbCancelar.setText("Limpar");
        jbCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbExcluir)
                    .addComponent(jbSalvar)
                    .addComponent(jbIncluir)
                    .addComponent(jbBuscar)
                    .addComponent(jbCancelar)
                    .addComponent(jbRelatorio))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jbBuscar)
                .addGap(56, 56, 56)
                .addComponent(jbIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jbSalvar)
                .addGap(56, 56, 56)
                .addComponent(jbExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jbCancelar)
                .addGap(56, 56, 56)
                .addComponent(jbRelatorio)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(895, 800));

        jlID.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlID.setText("ID");

        jlNome.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlNome.setText("Nome");

        jlCNPJ.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlCNPJ.setText("CNPJ");

        jlUF.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlUF.setText("UF");

        jlEmail.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlEmail.setText("Cidade");

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtCidade.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jlTelefone.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlTelefone.setText("Telefone");

        jlEndereco.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlEndereco.setText("Endereço");

        txtEndereco.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jlEmail1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlEmail1.setText("Email");

        try {
            txtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpj.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtUF.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jlUF1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlUF1.setText("Número");

        jlEmail2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlEmail2.setText("Bairro");

        txtNumeroEndereco.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtBairro.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlUF1)
                    .addComponent(txtNumeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlEmail1)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlCNPJ)
                                .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlTelefone)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtNome)
                        .addComponent(txtEndereco)
                        .addComponent(jlEndereco)
                        .addComponent(jlNome)
                        .addComponent(jlID)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlUF)
                                .addComponent(txtUF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlEmail)
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlEmail2)
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jlNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlCNPJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCnpj))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jlEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlUF1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlEmail2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlUF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jlEmail1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIncluirActionPerformed
        boolean status = fornecedorDao.conectar();

        if (status == true) {
            String strID = Integer.toString(fornecedorDao.ProximoId() + 1);
            txtID.setText(strID);
            txtNome.setText("");
            txtCnpj.setText("");
            txtTelefone.setText("");
            txtEndereco.setText("");
            txtBairro.setText("");
            txtNumeroEndereco.setText("");
            txtUF.setText("");
            txtCidade.setText("");
            txtEmail.setText("");
            fornecedorDao.desconectar();
            jbSalvar.setEnabled(true);
            txtNome.requestFocus();
            return;
        }

    }//GEN-LAST:event_jbIncluirActionPerformed

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        dispose();
        Principal principal = new Principal();
        principal.setVisible(true);
    }//GEN-LAST:event_jbVoltarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        int id = 0;
        String nome = "";
        String cnpj = "";
        String endereco = "";
        String cidade = "";
        String numero = "";
        String bairro = "";
        String uf = "";
        String telefone = "";
        String email = "";
        boolean status = fornecedorDao.conectar();
        int resposta;

        try {
            id = Integer.parseInt(txtID.getText());
            nome = txtNome.getText().toUpperCase();
            cnpj = txtCnpj.getText();
            endereco = txtEndereco.getText();
            cidade = txtCidade.getText().toUpperCase();
            numero = txtNumeroEndereco.getText();
            bairro = txtBairro.getText().toUpperCase();
            uf = txtUF.getText().toUpperCase();
            telefone = txtTelefone.getText();
            email = txtEmail.getText();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Preencha os campos corretamente");
        }
        if (status == false) {
            JOptionPane.showMessageDialog(null, "Erro de conexão");
        } else {
            Fornecedor fornecedor = new Fornecedor(id, nome, cnpj, endereco, numero, bairro, cidade, uf, telefone, email);

            if (fornecedorDao.consultarNome(nome).getNomeEmpresa().equals(nome)) {
                JOptionPane.showMessageDialog(rootPane, "Fornecedor " + fornecedor.getNomeEmpresa() + " já cadastrado com ID: " + fornecedor.getId());
                return;
            } else if (fornecedorDao.consultarCnpj(cnpj).getCnpj().equals(cnpj)) {
                JOptionPane.showMessageDialog(rootPane, "Fornecedor " + fornecedor.getNomeEmpresa() + " já cadastrado com CNPJ: " + fornecedor.getCnpj());
                return;
            }

            if (nome.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Preencha os campos corretamente");
            } else {
                resposta = fornecedorDao.salvar(fornecedor);

                if (resposta == 1) {
                    JOptionPane.showMessageDialog(null, "Fornecedor: " + nome + " cadastrado com sucesso!");
                } else if (resposta == 1062) {
                    JOptionPane.showMessageDialog(null, "Dados já cadastrado");
                }
            }
        }
        limparTela();
        fornecedorDao.desconectar();

    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        Object[] opcao = {"OK", "CANCELAR"};
        int id = Integer.parseInt(txtID.getText());
        boolean status = fornecedorDao.conectar();

        if (status == false) {
            JOptionPane.showMessageDialog(null, "Erro de conexão");
        } else {
            Fornecedor fornecedor = fornecedorDao.consultar(id);

            if (fornecedor == null) {
                JOptionPane.showMessageDialog(null, "Não foi encontrado um Fornecedor com ID " + id);
            } else {
                int confirmacao = JOptionPane.showOptionDialog(null, "Deseja Excluir o Fornecedor: " + fornecedor.getNomeEmpresa() + "?", "Aviso",
                        JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, opcao, opcao[0]);
                if (confirmacao == 0) {
                    fornecedorDao.excluir(id);
                    JOptionPane.showMessageDialog(null, "Fornecedor " + fornecedor.getNomeEmpresa() + " removido com sucesso!");
                    limparTela();
                    fornecedorDao.desconectar();
                    return;
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Exclusão cancelada");
                }
            }
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        int id = 0;
        boolean status = fornecedorDao.conectar();
        try {
            id = Integer.parseInt(txtID.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Formato Inválido!");
        }

        if (status == true) {
            Fornecedor fornecedor = fornecedorDao.consultar(id);
            if (fornecedor == null) {
                JOptionPane.showMessageDialog(null, "Não foi encontrado um fornecedor com ID " + id);
            } else {
                txtID.setText(String.valueOf(fornecedor.getId()));
                txtNome.setText(fornecedor.getNomeEmpresa());
                txtCnpj.setText(fornecedor.getCnpj());
                txtTelefone.setText(fornecedor.getTelefone());
                txtEndereco.setText(fornecedor.getEndereco());
                txtNumeroEndereco.setText(fornecedor.getNumero());
                txtBairro.setText(fornecedor.getBairro());
                txtUF.setText(fornecedor.getUf());
                txtCidade.setText(fornecedor.getCidade());
                txtEmail.setText(fornecedor.getEmail());
                jbExcluir.setEnabled(true);

            }
            fornecedorDao.desconectar();
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRelatorioActionPerformed
        relatorioFornecedor.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbRelatorioActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        limparTela();
    }//GEN-LAST:event_jbCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbIncluir;
    private javax.swing.JButton jbRelatorio;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JLabel jlCNPJ;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlEmail1;
    private javax.swing.JLabel jlEmail2;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JLabel jlUF;
    private javax.swing.JLabel jlUF1;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JFormattedTextField txtCnpj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumeroEndereco;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtUF;
    // End of variables declaration//GEN-END:variables

    public void limparTela() {
        txtBairro.setText("");
        txtCidade.setText("");
        txtCnpj.setText("");
        txtEmail.setText("");
        txtEndereco.setText("");
        txtID.setText("");
        txtNome.setText("");
        txtNumeroEndereco.setText("");
        txtTelefone.setText("");
        txtUF.setText("");
        jbExcluir.setEnabled(false);
        jbSalvar.setEnabled(false);
        txtID.requestFocus();
        jbBuscar.setEnabled(true);
    }
}
