/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import entidade.Cargo;
import entidade.Funcionario;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author LUKAS
 */
public class telaFuncionario extends javax.swing.JFrame {
    
    public static RelatorioFuncionario relatorioFuncionario = new RelatorioFuncionario();
    
    Funcionario funcionario = new Funcionario();
    Cargo cargo = new Cargo();

    /**
     * Creates new form Funcionario
     */
    public telaFuncionario() {
        initComponents();
        jbExcluir.setEnabled(false);
        jbSalvar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JbVoltar = new javax.swing.JButton();
        JbCargo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbBuscar = new javax.swing.JButton();
        jbIncluir = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbRelatorio = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlID = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jlCPF = new javax.swing.JLabel();
        jlTelefone = new javax.swing.JLabel();
        jlCargo = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtNomeCargo = new javax.swing.JTextField();
        jlEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jlUF = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        txtUF = new javax.swing.JTextField();
        jlUF1 = new javax.swing.JLabel();
        jlEmail2 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        txtNumeroEndereco = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        jlCargo1 = new javax.swing.JLabel();
        txtIdCargo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("FUNCIONÁRIO");

        JbVoltar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JbVoltar.setText("VOLTAR");
        JbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbVoltarActionPerformed(evt);
            }
        });

        JbCargo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JbCargo.setText("CARGO");
        JbCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 424, Short.MAX_VALUE)
                .addComponent(JbCargo)
                .addGap(80, 80, 80)
                .addComponent(JbVoltar)
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JbVoltar)
                    .addComponent(JbCargo))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(150, 800));

        jbBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbIncluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbIncluir.setText("Incluir");
        jbIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIncluirActionPerformed(evt);
            }
        });

        jbSalvar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbRelatorio.setText("Relatório");
        jbRelatorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbExcluir)
                    .addComponent(jbRelatorio)
                    .addComponent(jbSalvar)
                    .addComponent(jbIncluir)
                    .addComponent(jbBuscar))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jbBuscar)
                .addGap(50, 50, 50)
                .addComponent(jbIncluir)
                .addGap(50, 50, 50)
                .addComponent(jbSalvar)
                .addGap(50, 50, 50)
                .addComponent(jbExcluir)
                .addGap(50, 50, 50)
                .addComponent(jbRelatorio)
                .addGap(44, 44, 44))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(895, 800));

        jlID.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlID.setText("ID");

        jlNome.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlNome.setText("Nome");

        jlCPF.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlCPF.setText("CPF");

        jlTelefone.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlTelefone.setText("Telefone");

        jlCargo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlCargo.setText("Cargo");

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtCPF.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtTelefone.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtNomeCargo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jlEndereco.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlEndereco.setText("Endereço");

        txtEndereco.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jlUF.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlUF.setText("UF");

        jlEmail.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlEmail.setText("Cidade");

        txtUF.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jlUF1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlUF1.setText("Número");

        jlEmail2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlEmail2.setText("Bairro");

        txtCidade.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtNumeroEndereco.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtBairro.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jlCargo1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jlCargo1.setText("ID Cargo");

        txtIdCargo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtIdCargo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdCargoFocusLost(evt);
            }
        });
        txtIdCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdCargoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlUF1)
                            .addComponent(txtNumeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlUF)
                                    .addComponent(txtUF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlEmail)
                                    .addComponent(jlEmail2)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                                    .addComponent(txtCidade))))
                        .addGap(241, 241, 241))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlEndereco)
                            .addComponent(jlNome)
                            .addComponent(jlID)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlCPF)
                                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(205, 205, 205)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlTelefone)
                                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNome)
                                .addComponent(txtEndereco)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlCargo1)
                                        .addComponent(txtIdCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(132, 132, 132)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlCargo)
                                        .addComponent(txtNomeCargo, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jlID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jlNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jlCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jlEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlUF1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlEmail2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlUF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlCargo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlCargo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbVoltarActionPerformed
        dispose();
        Principal principal = new Principal();
        principal.setVisible(true);
    }//GEN-LAST:event_JbVoltarActionPerformed

    private void JbCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCargoActionPerformed
        telaCargo cargo = new telaCargo();
        cargo.setVisible(true);
        dispose();
    }//GEN-LAST:event_JbCargoActionPerformed

    private void jbIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIncluirActionPerformed
        String strID = Integer.toString(funcionario.proximoId());
        txtID.setText(strID);
        txtNome.setText("");
        txtCPF.setText("");
        txtTelefone.setText("");
        txtEndereco.setText("");
        txtBairro.setText("");
        txtNumeroEndereco.setText("");
        txtUF.setText("");
        txtCidade.setText("");
        txtNomeCargo.setText("");
        txtIdCargo.setText("");
        jbSalvar.setEnabled(true);
        jbExcluir.setEnabled(false);
    }//GEN-LAST:event_jbIncluirActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        int id = 0;

        try {
            id = Integer.parseInt(txtID.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Formato Inválido!");
            return;
        }

        for (Funcionario funcionario : funcionario.getFuncionarioList()) {
            if (funcionario.getId() == id) {
                String strId = Integer.toString(funcionario.getId());

                txtID.setText(strId);
                txtNome.setText(funcionario.getNomeFuncionario());
                txtCPF.setText(funcionario.getCpf());
                txtTelefone.setText(funcionario.getTelefone());
                txtEndereco.setText(funcionario.getEndereco());
                txtNumeroEndereco.setText(funcionario.getNumero());
                txtBairro.setText(funcionario.getBairro());
                txtUF.setText(funcionario.getUf());
                txtCidade.setText(funcionario.getCidade());
                txtNomeCargo.setText(funcionario.getNomeCargo());
                txtIdCargo.setText(Integer.toString(funcionario.getIdCargo()));
                jbExcluir.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        int id = 0;
        String nome = "";
        String cpf = "";
        String endereco = "";
        String numeroEndereco = "";
        String bairro = "";
        String cidade = "";
        String uf = "";
        String telefone = "";
        int idCargo = 0;
        String nomeCargo = "";

        try {
            id = Integer.parseInt(txtID.getText());
            nome = txtNome.getText();
            cpf = txtCPF.getText();
            endereco = txtEndereco.getText();
            numeroEndereco = txtNumeroEndereco.getText();
            bairro = txtBairro.getText();
            cidade = txtCidade.getText();
            uf = txtUF.getText();
            telefone = txtTelefone.getText();
            idCargo = Integer.parseInt(txtIdCargo.getText());
            nomeCargo = txtNomeCargo.getText();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos corretamente");
            return;
        }
        for (Funcionario funcionario : funcionario.getFuncionarioList()) {
            if (funcionario.getId() == id) {
                JOptionPane.showMessageDialog(rootPane, "ID: " + id + " já cadastrado para o funcionário " + funcionario.getNomeFuncionario());
                return;
            } else if (funcionario.getCpf() == cpf) {
                JOptionPane.showMessageDialog(rootPane, "CPF: " + cpf + " já cadastrado para o funcionário " + funcionario.getNomeFuncionario());
                return;
            }
        }

        Funcionario funcionario = new Funcionario(nome, cpf, endereco, numeroEndereco, bairro, cidade, uf, telefone, nomeCargo, idCargo);
        funcionario.inserir(funcionario);
        relatorioFuncionario.atualizarTabela();
        JOptionPane.showMessageDialog(rootPane, "Funcionário cadastrado com sucesso!"
                + "\nID: " + funcionario.getId() + "\nNome: " + funcionario.getNomeFuncionario() + ""
                + "CPF: " + funcionario.getCpf());

        txtID.setText("");
        txtNome.setText("");
        txtCPF.setText("");
        txtEndereco.setText("");
        txtNumeroEndereco.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtUF.setText("");
        txtTelefone.setText("");
        txtIdCargo.setText("");
        txtNomeCargo.setText("");
        jbExcluir.setEnabled(true);
        jbSalvar.setEnabled(false);

    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        Object[] opcao = {"OK", "CANCELAR"};
        int id = 0;
        try {
            id = Integer.parseInt(txtID.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Formato inválido");
        }
        for (Funcionario funcionario : funcionario.getFuncionarioList()) {
            if (funcionario.getId() == id) {
                int confirmacao = JOptionPane.showOptionDialog(null, "Deseja Excluir o Funcionário: " + funcionario.getNomeFuncionario() + "?", "Aviso",
                        JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, opcao, opcao[0]);
                if (confirmacao == 0) {
                    funcionario.getFuncionarioList().remove(funcionario);
                    relatorioFuncionario.atualizarTabela();
                    JOptionPane.showMessageDialog(null, "Funcionário " + funcionario.getNomeFuncionario() + " removido com sucesso!");
                    txtID.setText("");
                    txtNome.setText("");
                    txtCPF.setText("");
                    txtTelefone.setText("");
                    txtEndereco.setText("");
                    txtBairro.setText("");
                    txtNumeroEndereco.setText("");
                    txtUF.setText("");
                    txtCidade.setText("");
                    txtNomeCargo.setText("");
                    txtIdCargo.setText("");
                    return;
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Exclusão cancelada");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Não foi encontrado um funcionário com ID " + id);
            }
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void txtIdCargoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdCargoFocusLost
        int idCargo = 0;

        try {
            idCargo = Integer.parseInt(txtIdCargo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo ID CARGO corretamente");
            return;
        }

        for (Cargo cargo : cargo.cargoList) {
            if (cargo.getId() == idCargo) {
                txtNomeCargo.setText(cargo.getNome());
                return;
            } else {
                JOptionPane.showMessageDialog(rootPane, "Cargo não encontrado");
            }
        }
    }//GEN-LAST:event_txtIdCargoFocusLost

    private void txtIdCargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdCargoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int idCargo = 0;

            try {
                idCargo = Integer.parseInt(txtIdCargo.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Preencha o campo ID CARGO corretamente");
                return;
            }
            for (Cargo cargo : cargo.cargoList) {
                if (cargo.getId() == idCargo) {
                    txtNomeCargo.setText(cargo.getNome());
                    return;
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Cargo não encontrado");
                }
            }
        }
    }//GEN-LAST:event_txtIdCargoKeyPressed

    private void jbRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRelatorioActionPerformed
        relatorioFuncionario.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbCargo;
    private javax.swing.JButton JbVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbIncluir;
    private javax.swing.JButton jbRelatorio;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlCPF;
    private javax.swing.JLabel jlCargo;
    private javax.swing.JLabel jlCargo1;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlEmail2;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JLabel jlUF;
    private javax.swing.JLabel jlUF1;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIdCargo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeCargo;
    private javax.swing.JTextField txtNumeroEndereco;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtUF;
    // End of variables declaration//GEN-END:variables
}
