/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import estoque.MovimentacaoEstoque;
import estoque.MovimentacaoEstoqueDao;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import produto.ProdutoAcabado;
import produto.ProdutoAcabadoDao;
import produto.ProdutoCongelado;
import produto.ProdutoCongeladoDao;

/**
 *
 * @author LUKAS
 */
public class TransferenciaEstoque extends javax.swing.JFrame {

    MovimentacaoEstoque movimentacaoEstoque = new MovimentacaoEstoque();
    MovimentacaoEstoqueDao movimentacaoEstoqueDao = new MovimentacaoEstoqueDao();
    ProdutoCongelado produtoCongelado = new ProdutoCongelado();
    ProdutoCongeladoDao congeladoDao = new ProdutoCongeladoDao();
    ProdutoAcabado produtoAcabado = new ProdutoAcabado();
    ProdutoAcabadoDao acabadoDao = new ProdutoAcabadoDao();
    LocalDate data = LocalDate.now();
    DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    /**
     * Creates new form TransferenciaEstoque
     */
    public TransferenciaEstoque() {
        initComponents();
        jbExcluir.setEnabled(false);
        jbSalvar.setEnabled(false);
        txtData.setEditable(false);
        txtNomeProdutoAcabado.setEditable(false);
        txtEstoqueFinal.setEditable(false);
        txtEstoqueInicial.setEditable(false);
        txtIdProdutoCongelado.setEditable(false);
        txtNomeProdutoCongelado.setEditable(false);
        txtQuantidadeSaida.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbBuscar = new javax.swing.JButton();
        jbIncluir = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        jlID = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jlID2 = new javax.swing.JLabel();
        txtNomeProdutoAcabado = new javax.swing.JTextField();
        jlProduto1 = new javax.swing.JLabel();
        txtIdProdutoAcabado = new javax.swing.JTextField();
        jlQuantidade1 = new javax.swing.JLabel();
        txtQuantidadeAcabado = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jlID3 = new javax.swing.JLabel();
        txtNomeProdutoCongelado = new javax.swing.JTextField();
        jlProduto2 = new javax.swing.JLabel();
        txtIdProdutoCongelado = new javax.swing.JTextField();
        jlQuantidade2 = new javax.swing.JLabel();
        txtEstoqueInicial = new javax.swing.JTextField();
        txtQuantidadeSaida = new javax.swing.JTextField();
        jlQuantidade3 = new javax.swing.JLabel();
        txtEstoqueFinal = new javax.swing.JTextField();
        jlQuantidade4 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jlID1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("TRANSFERÊNCIA - ESTOQUE");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("VOLTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 453, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 800));

        jbBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbIncluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbIncluir.setText("Incluir");
        jbIncluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbIncluir.setNextFocusableComponent(txtIdProdutoAcabado);
        jbIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIncluirActionPerformed(evt);
            }
        });

        jbSalvar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setNextFocusableComponent(txtIdProdutoAcabado);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbBuscar)
                    .addComponent(jbIncluir)
                    .addComponent(jbSalvar)
                    .addComponent(jbExcluir)
                    .addComponent(btnLimpar))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jbBuscar)
                .addGap(50, 50, 50)
                .addComponent(jbIncluir)
                .addGap(50, 50, 50)
                .addComponent(jbSalvar)
                .addGap(50, 50, 50)
                .addComponent(jbExcluir)
                .addGap(50, 50, 50)
                .addComponent(btnLimpar)
                .addContainerGap(341, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(945, 800));

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jlID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlID.setText("ID");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrada"));

        jlID2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlID2.setText("ID");

        txtNomeProdutoAcabado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jlProduto1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlProduto1.setText("Produto");

        txtIdProdutoAcabado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIdProdutoAcabado.setNextFocusableComponent(txtQuantidadeAcabado);
        txtIdProdutoAcabado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdProdutoAcabadoFocusLost(evt);
            }
        });
        txtIdProdutoAcabado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdProdutoAcabadoKeyPressed(evt);
            }
        });

        jlQuantidade1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlQuantidade1.setText("Quantidade");

        txtQuantidadeAcabado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtQuantidadeAcabado.setNextFocusableComponent(jbSalvar);
        txtQuantidadeAcabado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantidadeAcabadoFocusLost(evt);
            }
        });
        txtQuantidadeAcabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeAcabadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlID2)
                            .addComponent(txtIdProdutoAcabado, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlProduto1)
                            .addComponent(txtNomeProdutoAcabado, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtQuantidadeAcabado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlQuantidade1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlProduto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeProdutoAcabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlID2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdProdutoAcabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jlQuantidade1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantidadeAcabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Saída"));

        jlID3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlID3.setText("ID");

        txtNomeProdutoCongelado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jlProduto2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlProduto2.setText("Produto");

        txtIdProdutoCongelado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jlQuantidade2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlQuantidade2.setText("Estoque Inicial");

        txtEstoqueInicial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtQuantidadeSaida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jlQuantidade3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlQuantidade3.setText("Saída");

        txtEstoqueFinal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jlQuantidade4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlQuantidade4.setText("Estoque Final");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlID3)
                            .addComponent(txtIdProdutoCongelado, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlProduto2)
                            .addComponent(txtNomeProdutoCongelado, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstoqueInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlQuantidade2))
                        .addGap(135, 135, 135)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantidadeSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlQuantidade3))
                        .addGap(106, 106, 106)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstoqueFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlQuantidade4))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jlProduto2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeProdutoCongelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jlID3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdProdutoCongelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jlQuantidade2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstoqueInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jlQuantidade3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantidadeSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jlQuantidade4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstoqueFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        txtData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jlID1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlID1.setText("Data");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlID)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlID1)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jlID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlID1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Estoque estoque = new Estoque();
        estoque.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIncluirActionPerformed
        boolean status = movimentacaoEstoqueDao.conectar();

        if (status == true) {
            String strID = Integer.toString(movimentacaoEstoqueDao.ProximoId() + 1);
            txtID.setText(strID);
            txtID.setEditable(false);
            String strData = data.format(fmt);
            txtData.setText(strData);
            txtData.setEditable(false);
            txtIdProdutoAcabado.setText("");
            txtNomeProdutoAcabado.setText("");
            txtQuantidadeAcabado.setText("");
            txtNomeProdutoAcabado.setEditable(false);

            txtIdProdutoCongelado.setText("");
            txtNomeProdutoCongelado.setText("");
            txtEstoqueInicial.setText("");
            txtQuantidadeSaida.setText("");
            txtEstoqueFinal.setText("");
            txtIdProdutoCongelado.setEditable(false);
            txtNomeProdutoCongelado.setEditable(false);
            txtEstoqueInicial.setEditable(false);
            txtEstoqueFinal.setEditable(false);
            txtQuantidadeSaida.setEditable(false);
            jbSalvar.setEnabled(true);

            jbIncluir.nextFocus();
            movimentacaoEstoqueDao.desconectar();
        }
    }//GEN-LAST:event_jbIncluirActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        int id = 0;
        String strData;
        LocalDate data = this.data;

        int idProdutoAcabado = 0;
        double quantidadeAcabado = 0.0;

        int idProdutoCongelado = 0;
        double estoqueInicial = 0.0;
        double estoqueSaida = 0.0;
        double estoqueFinal = 0.0;

        boolean status = movimentacaoEstoqueDao.conectar();
        int resposta;
        java.sql.Date sqlDate = null;

        try {
            id = Integer.parseInt(txtID.getText());
            strData = txtData.getText();
            data = LocalDate.parse(strData, fmt);
            idProdutoAcabado = Integer.parseInt(txtIdProdutoAcabado.getText());
            quantidadeAcabado = Double.parseDouble(txtQuantidadeAcabado.getText());
            idProdutoCongelado = Integer.parseInt(txtIdProdutoCongelado.getText());
            estoqueInicial = Double.parseDouble(txtEstoqueInicial.getText());
            estoqueSaida = Double.parseDouble(txtQuantidadeSaida.getText());
            estoqueFinal = Double.parseDouble(txtEstoqueFinal.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Formato Inválido!");
            return;
        }
        if (status == false) {
            JOptionPane.showMessageDialog(null, "Erro de conexão");
        } else {
            SimpleDateFormat conversor = new SimpleDateFormat("dd/MM/yyyy");
            try {
                Date dataConvertida = conversor.parse(strData);
                sqlDate = new java.sql.Date(dataConvertida.getTime());
            } catch (ParseException e) {
                System.out.println("Erro na conversão da data");
            }
            ProdutoCongelado congelado = new ProdutoCongelado();
            congelado.setId(idProdutoCongelado);

            ProdutoAcabado acabado = new ProdutoAcabado();
            acabado.setId(idProdutoAcabado);
            MovimentacaoEstoque estoque = new MovimentacaoEstoque(id, quantidadeAcabado, estoqueInicial, estoqueSaida, estoqueFinal, acabado, congelado, sqlDate);

            resposta = movimentacaoEstoqueDao.salvarTransferencia(estoque);

            if (resposta == 1) {
                JOptionPane.showMessageDialog(rootPane, "Entrada realizada com sucesso!");
            } else if (resposta == 1062) {
                JOptionPane.showMessageDialog(null, "Dados já cadastrado");
            }
            jbSalvar.setEnabled(false);
            movimentacaoEstoqueDao.desconectar();
        }
        limparTela();

    }//GEN-LAST:event_jbSalvarActionPerformed

    private void txtIdProdutoAcabadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdProdutoAcabadoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int idProdutoAcabado = 0;
            boolean status = acabadoDao.conectar();
            try {
                idProdutoAcabado = Integer.parseInt(txtIdProdutoAcabado.getText());
            } catch (NumberFormatException e) {

            }
            if (status == true) {
                ProdutoAcabado acabado = new ProdutoAcabado();
                acabado = acabadoDao.consultar(idProdutoAcabado);
                txtNomeProdutoAcabado.setText(acabado.getNome());
                String strIdProdutoCongelado = Integer.toString(acabado.getProdutoCongelado().getId());
                txtIdProdutoCongelado.setText(strIdProdutoCongelado);
                txtNomeProdutoCongelado.setText(acabado.getProdutoCongelado().getNome());
                String strEstoqueInicial = Double.toString(acabado.getProdutoCongelado().getQuantidadeEmEstoque());
                txtEstoqueInicial.setText(strEstoqueInicial);
                txtQuantidadeSaida.setText(txtQuantidadeAcabado.getText());
                movimentacaoEstoqueDao.desconectar();
                return;

            }
            JOptionPane.showMessageDialog(rootPane, "Produto não encontrado");
        }
    }//GEN-LAST:event_txtIdProdutoAcabadoKeyPressed

    private void txtQuantidadeAcabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeAcabadoActionPerformed
        double quantidade = 0.0;
        int idProdutoAcabado = 0;
        boolean status = TelaProduto.acabadoDao.conectar();
        try {
            idProdutoAcabado = Integer.parseInt(txtIdProdutoAcabado.getText());
            quantidade = Double.parseDouble(txtQuantidadeAcabado.getText());

        } catch (NumberFormatException e) {

        }
        if (quantidade > 0.0) {
            if (status == true) {
                ProdutoAcabado acabado = new ProdutoAcabado();
                acabado = TelaProduto.acabadoDao.consultar(idProdutoAcabado);

                double proporcao = acabado.getProdutoCongelado().getProporcao() * quantidade;
                String strProporcao = Double.toString(proporcao);
                txtQuantidadeSaida.setText(strProporcao);

                double estoqueFinal = acabado.getProdutoCongelado().getQuantidadeEmEstoque() - proporcao;
                String strEstoqueFinal = Double.toString(estoqueFinal);

                txtEstoqueFinal.setText(strEstoqueFinal);
                movimentacaoEstoqueDao.desconectar();
            }
        }

    }//GEN-LAST:event_txtQuantidadeAcabadoActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        Object[] options = {"OK", "CANCELAR"};
        int id = 0;
        boolean status = movimentacaoEstoqueDao.conectar();
        try {
            id = Integer.parseInt(txtID.getText());
        } catch (NullPointerException e) {

        }
        if (status == false) {
            JOptionPane.showMessageDialog(null, "Erro de conexão");
        } else {
            MovimentacaoEstoque movimentacaoEstoque = movimentacaoEstoqueDao.consultarCongelado(id);

            if (movimentacaoEstoque == null) {
                JOptionPane.showMessageDialog(rootPane, "Movimentação com ID: " + id + " não encontrado");
            } else {
                int confirmação = JOptionPane.showOptionDialog(null, "Deseja excluir a Movimentação: \nID:" + movimentacaoEstoque.getId() + "\nNome do Produto: " + movimentacaoEstoque.getProdutoAcabado().getNome() + "\nQuantidade: " + movimentacaoEstoque.getQuantidade(),
                        "Aviso", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
                if (confirmação == 0) {
                    status = movimentacaoEstoqueDao.excluir(id);
                    JOptionPane.showMessageDialog(rootPane, "Movimentação: " + id + "\nNome do Produto: " + movimentacaoEstoque.getProdutoAcabado().getNome() + "\nQuantidade: " + movimentacaoEstoque.getQuantidade()
                            + "\n\nRemovido com sucesso!");
                    limparTela();
                    movimentacaoEstoqueDao.desconectar();
                    return;
                } else if (confirmação == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Exclusão cancelada");
                    movimentacaoEstoqueDao.desconectar();
                    return;

                }
            }
        }

    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        int id = 0;
        boolean status = movimentacaoEstoqueDao.conectar();
        try {
            id = Integer.parseInt(txtID.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Formato Inválido!");
        }

        if (status == true) {
            MovimentacaoEstoque estoque = movimentacaoEstoqueDao.consultarCongelado(id);
            if (estoque == null) {
                JOptionPane.showMessageDialog(null, "Não foi encontrado uma movimentação com ID " + id + "");
            } else {
                txtData.setText(this.reverterData(String.valueOf(estoque.getData())));
                txtData.setEditable(false);
                txtIdProdutoAcabado.setText(Integer.toString(estoque.getProdutoAcabado().getId()));
                txtIdProdutoAcabado.setEditable(false);
                txtNomeProdutoAcabado.setText(estoque.getProdutoAcabado().getNome());
                txtNomeProdutoAcabado.setEditable(false);
                txtQuantidadeAcabado.setText(Double.toString(estoque.getProdutoAcabado().getQuantidadeEmEstoque()));
                txtQuantidadeAcabado.setEditable(false);
                txtIdProdutoCongelado.setText(Integer.toString(estoque.getProdutoCongelado().getId()));
                txtIdProdutoCongelado.setEditable(false);
                txtNomeProdutoCongelado.setText(estoque.getProdutoCongelado().getNome());
                txtNomeProdutoCongelado.setEditable(false);
                txtQuantidadeSaida.setText(Double.toString(estoque.getEstoqueSaida()));
                txtQuantidadeSaida.setEditable(false);
                txtEstoqueInicial.setText(Double.toString(estoque.getEstoqueInicial()));
                txtEstoqueInicial.setEditable(false);
                txtEstoqueFinal.setText(Double.toString(estoque.getEstoqueFinal()));
                txtEstoqueFinal.setEditable(false);
                movimentacaoEstoqueDao.desconectar();
                return;
            }
        }
        limparTela();
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void txtQuantidadeAcabadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantidadeAcabadoFocusLost
        double quantidade = 0.0;
        int idProdutoAcabado = 0;
        boolean status = TelaProduto.acabadoDao.conectar();
        try {
            idProdutoAcabado = Integer.parseInt(txtIdProdutoAcabado.getText());
            quantidade = Double.parseDouble(txtQuantidadeAcabado.getText());

        } catch (NumberFormatException e) {

        }
        if (quantidade > 0.0) {
            if (status == true) {
                ProdutoAcabado acabado = new ProdutoAcabado();
                acabado = TelaProduto.acabadoDao.consultar(idProdutoAcabado);

                double proporcao = acabado.getProdutoCongelado().getProporcao() * quantidade;
                String strProporcao = Double.toString(proporcao);
                txtQuantidadeSaida.setText(strProporcao);

                double estoqueFinal = acabado.getProdutoCongelado().getQuantidadeEmEstoque() - proporcao;
                String strEstoqueFinal = Double.toString(estoqueFinal);

                txtEstoqueFinal.setText(strEstoqueFinal);
                movimentacaoEstoqueDao.desconectar();
            }
        }
    }//GEN-LAST:event_txtQuantidadeAcabadoFocusLost

    private void txtIdProdutoAcabadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdProdutoAcabadoFocusLost
        int idProdutoAcabado = 0;
        boolean status = TelaProduto.acabadoDao.conectar();
        try {
            idProdutoAcabado = Integer.parseInt(txtIdProdutoAcabado.getText());
        } catch (NumberFormatException e) {

        }
        if (status == true) {
            ProdutoAcabado acabado = new ProdutoAcabado();
            acabado = TelaProduto.acabadoDao.consultar(idProdutoAcabado);

            txtNomeProdutoAcabado.setText(acabado.getNome());
            txtIdProdutoCongelado.setText(Integer.toString(acabado.getId()));
            txtNomeProdutoCongelado.setText(acabado.getProdutoCongelado().getNome());
            txtEstoqueInicial.setText(Double.toString(acabado.getProdutoCongelado().getQuantidadeEmEstoque()));
            txtQuantidadeSaida.setText(txtQuantidadeAcabado.getText());
            movimentacaoEstoqueDao.desconectar();
            return;
        }

        JOptionPane.showMessageDialog(rootPane, "Produto não encontrado");
    }//GEN-LAST:event_txtIdProdutoAcabadoFocusLost

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparTela();
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferenciaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferenciaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferenciaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferenciaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferenciaEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbIncluir;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlID1;
    private javax.swing.JLabel jlID2;
    private javax.swing.JLabel jlID3;
    private javax.swing.JLabel jlProduto1;
    private javax.swing.JLabel jlProduto2;
    private javax.swing.JLabel jlQuantidade1;
    private javax.swing.JLabel jlQuantidade2;
    private javax.swing.JLabel jlQuantidade3;
    private javax.swing.JLabel jlQuantidade4;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtEstoqueFinal;
    private javax.swing.JTextField txtEstoqueInicial;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIdProdutoAcabado;
    private javax.swing.JTextField txtIdProdutoCongelado;
    private javax.swing.JTextField txtNomeProdutoAcabado;
    private javax.swing.JTextField txtNomeProdutoCongelado;
    private javax.swing.JTextField txtQuantidadeAcabado;
    private javax.swing.JTextField txtQuantidadeSaida;
    // End of variables declaration//GEN-END:variables
      public String reverterData(String data) {
        String dia = data.substring(8);
        String mes = data.substring(5, 7);
        String ano = data.substring(0, 4);
        String sqlDate = dia + "/" + mes + "/" + ano;
        return sqlDate;
    }

    public void limparTela() {
        txtData.setText("");
        txtID.setText("");
        txtEstoqueFinal.setText("");
        txtIdProdutoCongelado.setText("");
        txtEstoqueInicial.setText("");
        txtNomeProdutoCongelado.setText("");
        txtIdProdutoAcabado.setText("");
        txtNomeProdutoAcabado.setText("");
        txtQuantidadeAcabado.setText("");
        txtQuantidadeSaida.setText("");
        jbBuscar.setEnabled(false);
        jbSalvar.setEnabled(false);
        txtID.requestFocus();
    }
}
